# Generated by Django 4.2.6 on 2023-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINAL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
